# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Polynom
version:      0.07
version_from: lib/Math/Polynom.pm
installdirs:  site
requires:
    accessors:                     0
    Carp:                          0
    constant:                      0
    Data::Dumper:                  2.10

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
